# .github/workflows/ci-cd.yml

name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd="mongo --eval 'db.adminCommand('ping')" --health-interval=10s --health-timeout=5s --health-retries=3"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Ensure this matches your local setup

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Run Tests
      env:
        DATABASE_URL: mongodb://localhost:27017/testdb
      run: npm run test

    - name: Docker Build
      run: docker-compose build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.beline021 }}
        DOCKER_PASSWORD: ${{ secrets.Beline@mugisha21 }}
      run: docker login -u $env:DOCKER_USERNAME -p $env:DOCKER_PASSWORD

    - name: Docker Build and Push
      run: |
        docker-compose build
        docker tag blog-api-node $env:DOCKER_USERNAME/blog-api:latest
        docker push $env:DOCKER_USERNAME/blog-api:latest

    - name: Deploy to Production
      env:
        SSH_PRIVATE_KEY: ${{ secrets.C:\Users\mn Technology Group\.ssh\id_rsa }}
        SERVER_USER: ${{ secrets.azureuser }}
        SERVER_IP: ${{ secrets.102.37.212.20 }}
      run: |
        ssh -i $SSH_PRIVATE_KEY $SERVER_USER@$SERVER_IP "docker pull $DOCKER_USERNAME/blog-api:latest && docker-compose up -d"
